[project]
name = "boost-and-broadside"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "pygame>=2.6.1",
    "stable-baselines3>=2.7.0",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
    "wandb>=0.22.2",
]
