_target_: boost_and_broadside.models.yemong.scaffolds.YemongTemporal

d_model: 256
n_layers: 6
input_dim: 9
target_dim: 9
learning_rate: 1e-4

scheduler:
  type: "warmup_constant"
  warmup:
    steps: 1000
    start_lr: 1e-7

lambda_state: 1.0
