_target_: boost_and_broadside.models.yemong.scaffolds.YemongSpatial

d_model: 256
n_layers: 4
n_heads: 4
input_dim: 14
action_dim: 12

spatial_layer:
  _target_: boost_and_broadside.models.components.layers.attention.RelationalAttention
  d_model: ${model.d_model}
  n_heads: ${model.n_heads}

lambda_power: 1.0
lambda_turn: 1.0
lambda_shoot: 1.0
